version: "3.3"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadbtest
    hostname: mariadbtest
    env_file:
      - ./mariadb.env

#GLPI Container
  glpi:
    image: matthewsponaugle/glpi:10.0.12
    container_name : glpitest
    hostname: glpitest
    ports:
      - "80:80"
